chore: update ci

diff --git a/.github/workflows/ci-js.yml b/.github/workflows/ci-js.yml
--- a/.github/workflows/ci-js.yml
+++ b/.github/workflows/ci-js.yml
@@ -41,12 +41,24 @@ jobs:
           args: "--package-managers NPM --output-formats JSON --output-dir ort-results"
           input-path: ".."
 
+      - name: Debug ORT Output
+        run: |
+          echo "Listing ORT output directory..."
+          ls -R ort-results || echo "ORT results directory not found!"
+          echo "Checking default ORT directories..."
+          ls -R ort || echo "Default ORT directory not found!"
+
+
       - name: Extract and set dependencies
         id: extract-dependencies
         run: |
-          echo "====== results"
-          cat ort-results/analyzer-result.json
-          dependencies=$(jq -r '.analyzer.result.projects[].scopes[].dependencies[].id' ort-results/analyzer-result.json | tr '\n' ',')
+          ORT_JSON_PATH=$(find ort-results ort -name "analyzer-result.json" 2>/dev/null | head -n 1)
+          if [[ -z "$ORT_JSON_PATH" ]]; then
+            echo "Error: analyzer-result.json not found!"
+            exit 1
+          fi
+          echo "Found ORT JSON file at $ORT_JSON_PATH"
+          dependencies=$(jq -r '.analyzer.result.projects[].scopes[].dependencies[].id' "$ORT_JSON_PATH" | tr '\n' ',')
           echo "packages=${dependencies}" >> $GITHUB_ENV
 
       - name: Check for New Dependencies
